/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckoutPanel.java
 *
 * Created on Feb 22, 2012, 2:43:43 PM
 */
package dkgg2012group22imat.view.checkout;

/**
 *
 * @author jonas
 */
public class CheckoutPanel extends javax.swing.JPanel {

    /** Creates new form CheckoutPanel */
    public CheckoutPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontaktInfoLabel = new javax.swing.JLabel();
        nameLabeel = new javax.swing.JLabel();
        surNameLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        postalAdressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        surNameTextField = new javax.swing.JTextField();
        adressTextField = new javax.swing.JTextField();
        postAdressnameTextFieldTextField = new javax.swing.JTextField();
        phoneNumbernameTextField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(CheckoutPanel.class);
        kontaktInfoLabel.setText(resourceMap.getString("kontaktInfoLabel.text")); // NOI18N
        kontaktInfoLabel.setName("kontaktInfoLabel"); // NOI18N

        nameLabeel.setText(resourceMap.getString("nameLabeel.text")); // NOI18N
        nameLabeel.setName("nameLabeel"); // NOI18N

        surNameLabel.setText(resourceMap.getString("surNameLabel.text")); // NOI18N
        surNameLabel.setName("surNameLabel"); // NOI18N

        adressLabel.setText(resourceMap.getString("adressLabel.text")); // NOI18N
        adressLabel.setName("adressLabel"); // NOI18N

        postalAdressLabel.setText(resourceMap.getString("postalAdressLabel.text")); // NOI18N
        postalAdressLabel.setName("postalAdressLabel"); // NOI18N

        phoneNumberLabel.setText(resourceMap.getString("phoneNumberLabel.text")); // NOI18N
        phoneNumberLabel.setName("phoneNumberLabel"); // NOI18N

        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        surNameTextField.setText(resourceMap.getString("surNameTextField.text")); // NOI18N
        surNameTextField.setName("surNameTextField"); // NOI18N

        adressTextField.setText(resourceMap.getString("adressTextField.text")); // NOI18N
        adressTextField.setName("adressTextField"); // NOI18N

        postAdressnameTextFieldTextField.setText(resourceMap.getString("postAdressnameTextFieldTextField.text")); // NOI18N
        postAdressnameTextFieldTextField.setName("postAdressnameTextFieldTextField"); // NOI18N

        phoneNumbernameTextField.setText(resourceMap.getString("phoneNumbernameTextField.text")); // NOI18N
        phoneNumbernameTextField.setName("phoneNumbernameTextField"); // NOI18N

        filler1.setName("filler1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kontaktInfoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(surNameLabel)
                            .addComponent(nameLabeel)
                            .addComponent(postalAdressLabel)
                            .addComponent(phoneNumberLabel)
                            .addComponent(adressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postAdressnameTextFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumbernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kontaktInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabeel)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(surNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalAdressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postAdressnameTextFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneNumbernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberLabel)))
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressLabel;
    private javax.swing.JTextField adressTextField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel kontaktInfoLabel;
    private javax.swing.JLabel nameLabeel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumbernameTextField;
    private javax.swing.JTextField postAdressnameTextFieldTextField;
    private javax.swing.JLabel postalAdressLabel;
    private javax.swing.JLabel surNameLabel;
    private javax.swing.JTextField surNameTextField;
    // End of variables declaration//GEN-END:variables
}
