/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntrancePanel.java
 *
 * Created on Feb 19, 2012, 9:29:52 PM
 */
package dkgg2012group22imat.view.entrance;


/**
 *
 * @author jonas
 */
public class EntrancePanel extends javax.swing.JPanel {

    /** Creates new form EntrancePanel */
    public EntrancePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper1 = new dkgg2012group22imat.view.entrance.carts.CartsWrapper();
        cartsWrapper1 = new dkgg2012group22imat.view.entrance.carts.CartsWrapper();
        contentPanel = new javax.swing.JPanel();
        spotlightProductsPanel1 = new dkgg2012group22imat.view.entrance.SpotlightProductsPanel();
        favoriteProductsPanel1 = new dkgg2012group22imat.view.entrance.FavoriteProductsPanel();

        wrapper1.setName("wrapper1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(EntrancePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        cartsWrapper1.setBackground(resourceMap.getColor("cartsWrapper1.background")); // NOI18N
        cartsWrapper1.setName("cartsWrapper1"); // NOI18N
        cartsWrapper1.setOpaque(false);
        add(cartsWrapper1, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(resourceMap.getColor("contentPanel.background")); // NOI18N
        contentPanel.setName("contentPanel"); // NOI18N
        contentPanel.setLayout(new java.awt.GridLayout(2, 1));

        spotlightProductsPanel1.setName("spotlightProductsPanel1"); // NOI18N
        spotlightProductsPanel1.setOpaque(false);
        contentPanel.add(spotlightProductsPanel1);

        favoriteProductsPanel1.setBackground(resourceMap.getColor("favoriteProductsPanel1.background")); // NOI18N
        favoriteProductsPanel1.setName("favoriteProductsPanel1"); // NOI18N
        contentPanel.add(favoriteProductsPanel1);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dkgg2012group22imat.view.entrance.carts.CartsWrapper cartsWrapper1;
    private javax.swing.JPanel contentPanel;
    private dkgg2012group22imat.view.entrance.FavoriteProductsPanel favoriteProductsPanel1;
    private dkgg2012group22imat.view.entrance.SpotlightProductsPanel spotlightProductsPanel1;
    private dkgg2012group22imat.view.entrance.carts.CartsWrapper wrapper1;
    // End of variables declaration//GEN-END:variables
}
