/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShopPanel.java
 *
 * Created on 2012-feb-24, 13:43:40
 */
package dkgg2012group22imat.view.shop;

/**
 *
 * @author Simon
 */
public class ShopPanel extends javax.swing.JPanel {

    /** Creates new form ShopPanel */
    public ShopPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriesPanel1 = new dkgg2012group22imat.view.shop.CategoriesPanel();
        productsPanel1 = new dkgg2012group22imat.view.shop.ProductsPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        categoriesPanel1.setName("categoriesPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout categoriesPanel1Layout = new org.jdesktop.layout.GroupLayout(categoriesPanel1);
        categoriesPanel1.setLayout(categoriesPanel1Layout);
        categoriesPanel1Layout.setHorizontalGroup(
            categoriesPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        categoriesPanel1Layout.setVerticalGroup(
            categoriesPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        add(categoriesPanel1, java.awt.BorderLayout.WEST);

        productsPanel1.setName("productsPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout productsPanel1Layout = new org.jdesktop.layout.GroupLayout(productsPanel1);
        productsPanel1.setLayout(productsPanel1Layout);
        productsPanel1Layout.setHorizontalGroup(
            productsPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        productsPanel1Layout.setVerticalGroup(
            productsPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        add(productsPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dkgg2012group22imat.view.shop.CategoriesPanel categoriesPanel1;
    private dkgg2012group22imat.view.shop.ProductsPanel productsPanel1;
    // End of variables declaration//GEN-END:variables
}
