/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShopPanel.java
 *
 * Created on 2012-feb-24, 13:43:40
 */
package dkgg2012group22imat.view.shop;

import dkgg2012group22imat.controller.shop.ShopPanelController;
import dkgg2012group22imat.model.Model;
import dkgg2012group22imat.view.ProductsPanel;
import java.awt.BorderLayout;

/**
 *
 * @author Simon
 */
public class ShopPanel extends javax.swing.JPanel {
    
    ShopPanelController controller;

    /** Creates new form ShopPanel */
    public ShopPanel() {
        initComponents();
        this.controller = new ShopPanelController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        leftPanel.setName("leftPanel"); // NOI18N
        leftPanel.setLayout(new java.awt.GridLayout(1, 0));
        add(leftPanel, java.awt.BorderLayout.WEST);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(ShopPanel.class);
        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N
        jPanel1.add(titleLabel, java.awt.BorderLayout.NORTH);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel leftPanel;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
