/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntrancePanel.java
 *
 * Created on Feb 19, 2012, 9:29:52 PM
 */
package dkgg2012group22imat.view.entrance;

import dkgg2012group22imat.controller.entrance.EntrancePanelController;

/**
 *
 * @author jonas
 */
public class EntrancePanel extends javax.swing.JPanel {
EntrancePanelController controller;

    /** Creates new form EntrancePanel */
    public EntrancePanel() {
        initComponents();
        controller = new EntrancePanelController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historyCartsPanel1 = new dkgg2012group22imat.view.entrance.HistoryCartsPanel();
        spotlightProductsPanel1 = new dkgg2012group22imat.view.entrance.SpotlightProductsPanel();
        favoriteProductsPanel1 = new dkgg2012group22imat.view.entrance.FavoriteProductsPanel();
        favoriteCartsPanel1 = new dkgg2012group22imat.view.entrance.FavoriteCartsPanel();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        historyCartsPanel1.setName("historyCartsPanel1"); // NOI18N
        jScrollPane1.setViewportView(historyCartsPanel1);

        spotlightProductsPanel1.setName("spotlightProductsPanel1"); // NOI18N

        favoriteProductsPanel1.setName("favoriteProductsPanel1"); // NOI18N

        favoriteCartsPanel1.setName("favoriteCartsPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoriteCartsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spotlightProductsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoriteProductsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spotlightProductsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(favoriteCartsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoriteProductsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dkgg2012group22imat.view.entrance.FavoriteCartsPanel favoriteCartsPanel1;
    private dkgg2012group22imat.view.entrance.FavoriteProductsPanel favoriteProductsPanel1;
    private dkgg2012group22imat.view.entrance.HistoryCartsPanel historyCartsPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private dkgg2012group22imat.view.entrance.SpotlightProductsPanel spotlightProductsPanel1;
    // End of variables declaration//GEN-END:variables
}
