/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuperCartsPanel.java
 *
 * Created on Feb 26, 2012, 7:52:05 PM
 */
package dkgg2012group22imat.view.entrance.carts;

/**
 *
 * @author jonas
 */
public class SuperCartsPanel extends javax.swing.JPanel {
    SuperCartsPanelController controller;
    /** Creates new form SuperCartsPanel */
    public SuperCartsPanel(CartsWrapperController parent) {
        initComponents();
        controller = new SuperCartsPanelController(parent, this);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savedCartsPanelWrapper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        savedCartsScrollPane = new javax.swing.JScrollPane();
        favoriteCartsPanel = new javax.swing.JPanel();
        historyCartsPanelWrapper = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        historyCartsScrollPane = new javax.swing.JScrollPane();
        historyCartsPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(270, 0));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        savedCartsPanelWrapper.setName("savedCartsPanelWrapper"); // NOI18N
        savedCartsPanelWrapper.setOpaque(false);
        savedCartsPanelWrapper.setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(SuperCartsPanel.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        savedCartsPanelWrapper.add(jLabel1, java.awt.BorderLayout.NORTH);

        savedCartsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        savedCartsScrollPane.setName("savedCartsScrollPane"); // NOI18N
        savedCartsScrollPane.setOpaque(false);

        favoriteCartsPanel.setName("favoriteCartsPanel"); // NOI18N
        favoriteCartsPanel.setOpaque(false);
        favoriteCartsPanel.setLayout(new javax.swing.BoxLayout(favoriteCartsPanel, javax.swing.BoxLayout.Y_AXIS));
        savedCartsScrollPane.setViewportView(favoriteCartsPanel);

        savedCartsPanelWrapper.add(savedCartsScrollPane, java.awt.BorderLayout.CENTER);

        add(savedCartsPanelWrapper);

        historyCartsPanelWrapper.setName("historyCartsPanelWrapper"); // NOI18N
        historyCartsPanelWrapper.setOpaque(false);
        historyCartsPanelWrapper.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        historyCartsPanelWrapper.add(jLabel2, java.awt.BorderLayout.NORTH);

        historyCartsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        historyCartsScrollPane.setName("historyCartsScrollPane"); // NOI18N
        historyCartsScrollPane.setOpaque(false);

        historyCartsPanel.setName("historyCartsPanel"); // NOI18N
        historyCartsPanel.setOpaque(false);
        historyCartsPanel.setLayout(new javax.swing.BoxLayout(historyCartsPanel, javax.swing.BoxLayout.Y_AXIS));
        historyCartsScrollPane.setViewportView(historyCartsPanel);

        historyCartsPanelWrapper.add(historyCartsScrollPane, java.awt.BorderLayout.CENTER);

        add(historyCartsPanelWrapper);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel favoriteCartsPanel;
    public javax.swing.JPanel historyCartsPanel;
    private javax.swing.JPanel historyCartsPanelWrapper;
    private javax.swing.JScrollPane historyCartsScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel savedCartsPanelWrapper;
    private javax.swing.JScrollPane savedCartsScrollPane;
    // End of variables declaration//GEN-END:variables
}
