/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuperCartsPanel.java
 *
 * Created on Feb 26, 2012, 7:52:05 PM
 */
package dkgg2012group22imat.view.entrance.carts;

/**
 *
 * @author jonas
 */
public class SuperCartsPanel extends javax.swing.JPanel {
    SuperCartsPanelController controller;
    /** Creates new form SuperCartsPanel */
    public SuperCartsPanel(CartsWrapperController parent) {
        initComponents();
        controller = new SuperCartsPanelController(parent, this);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savedCartsPanelWrapper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        savedCartsScrollPane = new javax.swing.JScrollPane();
        favoriteCartsPanel = new javax.swing.JPanel();
        historyCartsPanelWrapper = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        historyCartsScrollPane = new javax.swing.JScrollPane();
        historyCartsPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        savedCartsPanelWrapper.setName("savedCartsPanelWrapper"); // NOI18N
        savedCartsPanelWrapper.setLayout(new javax.swing.BoxLayout(savedCartsPanelWrapper, javax.swing.BoxLayout.PAGE_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(SuperCartsPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        savedCartsPanelWrapper.add(jLabel1);

        savedCartsScrollPane.setName("savedCartsScrollPane"); // NOI18N

        favoriteCartsPanel.setName("favoriteCartsPanel"); // NOI18N
        savedCartsScrollPane.setViewportView(favoriteCartsPanel);

        savedCartsPanelWrapper.add(savedCartsScrollPane);

        add(savedCartsPanelWrapper);

        historyCartsPanelWrapper.setName("historyCartsPanelWrapper"); // NOI18N
        historyCartsPanelWrapper.setLayout(new javax.swing.BoxLayout(historyCartsPanelWrapper, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        historyCartsPanelWrapper.add(jLabel2);

        historyCartsScrollPane.setName("historyCartsScrollPane"); // NOI18N

        historyCartsPanel.setName("historyCartsPanel"); // NOI18N
        historyCartsScrollPane.setViewportView(historyCartsPanel);

        historyCartsPanelWrapper.add(historyCartsScrollPane);

        add(historyCartsPanelWrapper);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel favoriteCartsPanel;
    public javax.swing.JPanel historyCartsPanel;
    private javax.swing.JPanel historyCartsPanelWrapper;
    private javax.swing.JScrollPane historyCartsScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel savedCartsPanelWrapper;
    private javax.swing.JScrollPane savedCartsScrollPane;
    // End of variables declaration//GEN-END:variables
}
