/*
 * ItemPanel.java
 *
 * Created on Feb 17, 2012, 2:26:49 PM
 */
package dkgg2012group22imat.view;

import dkgg2012group22imat.controller.CartProductController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import org.jdesktop.application.ResourceMap;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author jonas
 */
public class CartProductPanel extends javax.swing.JPanel {

    CartProductController controller;
    boolean inside;
    Dimension small = new Dimension(150, 150);
    Dimension big = new Dimension(200, 200);
    ShoppingItem si;
    

    /** Creates new form ItemPanel */
    public CartProductPanel(ShoppingItem si) {
        initComponents();
        controller = new CartProductController(si, this);
        this.setAmount(si.getAmount());
    }
    
    @Override
    public void paintComponent(Graphics g) {
        ResourceMap resourceMap = DKGG2012Group22iMatApp.getApplication().getContext().getResourceMap(CartProductPanel.class);
        
        GUtilities.drawTiled(g, this.getSize(), resourceMap.getImageIcon("JPanel.background"));
        
        g.setColor(new Color(204,204,204));
        g.drawRect(-1, -1, this.getWidth()+1, this.getHeight());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        favoriteToggleButton = new javax.swing.JToggleButton();
        quantitySpinner = new javax.swing.JSpinner();
        deleteButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(CartProductPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMaximumSize(new java.awt.Dimension(2147483647, 85));
        setMinimumSize(new java.awt.Dimension(160, 85));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 85));
        setRequestFocusEnabled(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productNameLabel.setText(resourceMap.getString("productNameLabel.text")); // NOI18N
        productNameLabel.setName("productNameLabel"); // NOI18N
        add(productNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 113, -1));

        iconLabel.setText(resourceMap.getString("iconLabel.text")); // NOI18N
        iconLabel.setName("iconLabel"); // NOI18N
        add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        priceLabel.setBackground(resourceMap.getColor("priceLabel.background")); // NOI18N
        priceLabel.setText(resourceMap.getString("priceLabel.text")); // NOI18N
        priceLabel.setName("priceLabel"); // NOI18N
        add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        favoriteToggleButton.setIcon(resourceMap.getIcon("favoriteToggleButton.icon")); // NOI18N
        favoriteToggleButton.setText(resourceMap.getString("favoriteToggleButton.text")); // NOI18N
        favoriteToggleButton.setBorderPainted(false);
        favoriteToggleButton.setContentAreaFilled(false);
        favoriteToggleButton.setDisabledIcon(resourceMap.getIcon("favoriteToggleButton.disabledIcon")); // NOI18N
        favoriteToggleButton.setDisabledSelectedIcon(resourceMap.getIcon("favoriteToggleButton.disabledSelectedIcon")); // NOI18N
        favoriteToggleButton.setFocusPainted(false);
        favoriteToggleButton.setName("favoriteToggleButton"); // NOI18N
        favoriteToggleButton.setPressedIcon(resourceMap.getIcon("favoriteToggleButton.pressedIcon")); // NOI18N
        favoriteToggleButton.setRequestFocusEnabled(false);
        favoriteToggleButton.setRolloverIcon(resourceMap.getIcon("favoriteToggleButton.rolloverIcon")); // NOI18N
        favoriteToggleButton.setRolloverSelectedIcon(resourceMap.getIcon("favoriteToggleButton.rolloverSelectedIcon")); // NOI18N
        favoriteToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteToggleButtonActionPerformed(evt);
            }
        });
        add(favoriteToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        quantitySpinner.setMinimumSize(new java.awt.Dimension(37, 26));
        quantitySpinner.setName("quantitySpinner"); // NOI18N
        quantitySpinner.setPreferredSize(new java.awt.Dimension(70, 26));
        quantitySpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quantitySpinnerMouseEntered(evt);
            }
        });
        quantitySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantitySpinnerStateChanged(evt);
            }
        });
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 25));
        quantitySpinner.setUI(new StyledSpinnerUI());

        deleteButton.setText(resourceMap.getString("deleteButton.text")); // NOI18N
        deleteButton.setName("deleteButton"); // NOI18N
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    controller.hooverd();
}//GEN-LAST:event_formMouseEntered

private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    controller.dehoover();
}//GEN-LAST:event_formMouseExited

private void favoriteToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteToggleButtonActionPerformed
    controller.favorize();
}//GEN-LAST:event_favoriteToggleButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_deleteButtonActionPerformed

private void quantitySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantitySpinnerStateChanged
    controller.spinnerChanged((Integer)quantitySpinner.getValue());
}//GEN-LAST:event_quantitySpinnerStateChanged

private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
    controller.hooverd();
}//GEN-LAST:event_deleteButtonMouseEntered

private void quantitySpinnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantitySpinnerMouseEntered
    controller.hooverd();
}//GEN-LAST:event_quantitySpinnerMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton deleteButton;
    public javax.swing.JToggleButton favoriteToggleButton;
    public javax.swing.JLabel iconLabel;
    public javax.swing.JLabel priceLabel;
    public javax.swing.JLabel productNameLabel;
    public javax.swing.JSpinner quantitySpinner;
    // End of variables declaration//GEN-END:variables

    public int getAmount() {
        return Integer.parseInt(quantitySpinner.getValue().toString());
    }
    public void setAmount(double amount) {
        //TODO WARNING: double->int typecast
        quantitySpinner.setValue(new Integer((int)amount));
    }
}
