/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CartWithProductsPanel.java
 *
 * Created on 2012-feb-22, 13:54:38
 */
package dkgg2012group22imat.view;

import dkgg2012group22imat.controller.CartWithProductsPanelController;

/**
 *
 * @author magnushuttu
 */
public class CartWithProductsPanel extends javax.swing.JPanel {

    CartWithProductsPanelController controller;
    /** Creates new form CartWithProductsPanel */
    public CartWithProductsPanel() {
        initComponents();
        controller = new CartWithProductsPanelController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
