/*
 * DKGG2012Group22iMatView.java
 */

package dkgg2012group22imat.view;

import dkgg2012group22imat.controller.iMatViewController;
import dkgg2012group22imat.controller.iMatViewController.MainView;
import java.awt.CardLayout;
import java.util.HashSet;
import java.util.Set;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.OverlayLayout;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * The application's main frame.
 */
public class DKGG2012Group22iMatView extends FrameView {
    
    private iMatViewController controller;
    

    public DKGG2012Group22iMatView(SingleFrameApplication app) {
        super(app);

        controller = new iMatViewController(this);
        //initComponents();
        //animationPanel.setLayout(new OverlayLayout(animationPanel));
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DKGG2012Group22iMatApp.getApplication().getMainFrame();
            aboutBox = new DKGG2012Group22iMatAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DKGG2012Group22iMatApp.getApplication().show(aboutBox);
    }
    
    public void setView(MainView viewEnum) {
        switch(viewEnum) {
            case ENTRANCE:
                ((CardLayout)mainContentPanel.getLayout()).show(mainContentPanel,"ENTRANCE");
                break;
            case SHOP:
                ((CardLayout)mainContentPanel.getLayout()).show(mainContentPanel,"SHOP");
                break;
            case CHECKOUT:
                ((CardLayout)mainContentPanel.getLayout()).show(mainContentPanel,"CHECKOUT");
                break;
            default:
                setView(MainView.ENTRANCE);
        }
        
    }
    
    public iMatViewController getController() {
        return controller;
    }

    public JPanel getAnimationPanel() {
        return animationPanel;
    }
    
    public void init() {
        initComponents();
        
        jLayeredPane1.setLayout(new OverlayLayout(jLayeredPane1));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        animationPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainContentPanel = new javax.swing.JPanel();

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getResourceMap(DKGG2012Group22iMatView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(dkgg2012group22imat.view.DKGG2012Group22iMatApp.class).getContext().getActionMap(DKGG2012Group22iMatView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        animationPanel.setBackground(resourceMap.getColor("animationPanel.background")); // NOI18N
        animationPanel.setName("animationPanel"); // NOI18N
        animationPanel.setOpaque(false);
        animationPanel.setLayout(null);
        animationPanel.setBounds(0, 0, 810, 700);
        jLayeredPane1.add(animationPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        mainContentPanel.setBackground(resourceMap.getColor("mainContentPanel.background")); // NOI18N
        mainContentPanel.setName("mainContentPanel"); // NOI18N
        mainContentPanel.setOpaque(false);
        mainContentPanel.setLayout(new java.awt.CardLayout());
        jPanel1.add(mainContentPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        mainPanel.setBounds(0, 0, 0, 0);
        jLayeredPane1.add(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setComponent(jLayeredPane1);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animationPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
}
