/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntranceTestFrame.java
 *
 * Created on Feb 21, 2012, 9:10:10 AM
 */
package dkgg2012group22imat.view;

import dkgg2012group22imat.model.Model;

/**
 *
 * @author jonas
 */
public class EntranceTestFrame extends javax.swing.JFrame {

    /** Creates new form EntranceTestFrame */
    public EntranceTestFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        favoriteProductsPanel1 = new dkgg2012group22imat.view.entrance.FavoriteProductsPanel();
        entrancePanel1 = new dkgg2012group22imat.view.entrance.EntrancePanel();

        favoriteProductsPanel1.setName("favoriteProductsPanel1"); // NOI18N

        setDefaultCloseOperation(Model.getInstance().shutDown());
        setName("Form"); // NOI18N

        entrancePanel1.setName("entrancePanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrancePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrancePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EntranceTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dkgg2012group22imat.view.entrance.EntrancePanel entrancePanel1;
    private dkgg2012group22imat.view.entrance.FavoriteProductsPanel favoriteProductsPanel1;
    // End of variables declaration//GEN-END:variables
}
